CREATE TABLE "company_daily_active_assignments" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"company_id" uuid NOT NULL,
	"snapshot_date" date NOT NULL,
	"active_team_id" uuid,
	"active_manager_id" uuid,
	"active_time" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "company_daily_active_assignments_company_id_snapshot_date_key" UNIQUE("company_id","snapshot_date")
);
--> statement-breakpoint
CREATE TABLE "customer_time_report_defaults" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "customer_time_report_defaults_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"title" varchar(200) DEFAULT 'Saved filter' NOT NULL,
	"filters" jsonb NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_by" uuid
);
--> statement-breakpoint
CREATE TABLE "customer_weekly_recap_cells" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"team_id" uuid NOT NULL,
	"company_id" uuid NOT NULL,
	"week_start" date NOT NULL,
	"week_end" date NOT NULL,
	"iso_year" integer NOT NULL,
	"iso_week" integer NOT NULL,
	"is_embedded" boolean DEFAULT false NOT NULL,
	"client_time_hours" integer DEFAULT 0 NOT NULL,
	"tracker_reported_seconds" bigint DEFAULT 0 NOT NULL,
	"computed_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "customer_weekly_recap_cells_team_company_week_uid" UNIQUE("team_id","company_id","week_start")
);
--> statement-breakpoint
CREATE TABLE "dashboard_announcements" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"title" varchar(500) NOT NULL,
	"body" text DEFAULT '' NOT NULL,
	"target_roles" text[],
	"is_published" boolean DEFAULT false NOT NULL,
	"starts_at" timestamp with time zone,
	"ends_at" timestamp with time zone,
	"sort_order" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" uuid
);
--> statement-breakpoint
CREATE TABLE "global_announcement" (
	"id" uuid PRIMARY KEY NOT NULL,
	"message" text DEFAULT '' NOT NULL,
	"is_enabled" boolean DEFAULT false NOT NULL,
	"starts_at" timestamp with time zone,
	"ends_at" timestamp with time zone,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_by" uuid
);
--> statement-breakpoint
CREATE TABLE "job_types" (
	"slug" varchar(64) PRIMARY KEY NOT NULL,
	"title" varchar(255) NOT NULL,
	"sort_order" integer DEFAULT 0 NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "project_statuses" (
	"id" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "project_statuses_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"project_id" uuid NOT NULL,
	"title" varchar(100) NOT NULL,
	"slug" varchar(50) NOT NULL,
	"color" varchar(20) DEFAULT '#d9d9d9' NOT NULL,
	"sort_order" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "project_statuses_project_id_slug_key" UNIQUE("project_id","slug")
);
--> statement-breakpoint
CREATE TABLE "projects" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"title" varchar(255) NOT NULL,
	"description" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "recap_snapshots" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"title" varchar(500) NOT NULL,
	"period_start" date NOT NULL,
	"period_end" date NOT NULL,
	"period_type" varchar(16) NOT NULL,
	"team_ids" jsonb NOT NULL,
	"team_key" varchar(2000) NOT NULL,
	"payload" jsonb NOT NULL,
	"created_by" uuid,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "slack_ticket_notification_rules" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"name" varchar(255),
	"webhook_url" text NOT NULL,
	"is_enabled" boolean DEFAULT true NOT NULL,
	"filter" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"sort_order" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "system_activity_log" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"actor_user_id" uuid,
	"actor_role" varchar(32) DEFAULT 'agent' NOT NULL,
	"category" varchar(32) NOT NULL,
	"action" varchar(64) NOT NULL,
	"entity_type" varchar(64),
	"entity_id" varchar(255),
	"metadata" jsonb,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "ticket_ai_summaries" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"ticket_id" integer NOT NULL,
	"anchor_type" varchar(32) NOT NULL,
	"focal_comment_id" uuid,
	"summary" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"checklist" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"created_by_user_id" uuid,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"applied_to_comment_at" timestamp with time zone,
	"applied_to_description_at" timestamp with time zone,
	"applied_to_checklist_at" timestamp with time zone
);
--> statement-breakpoint
ALTER TABLE "company_ai_system_template" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "company_content_generation_history" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "company_content_planners" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "company_content_templates" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "content_planner_channels" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "content_planner_intents" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "content_planner_topic_types" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
DROP TABLE "company_ai_system_template" CASCADE;--> statement-breakpoint
DROP TABLE "company_content_generation_history" CASCADE;--> statement-breakpoint
DROP TABLE "company_content_planners" CASCADE;--> statement-breakpoint
DROP TABLE "company_content_templates" CASCADE;--> statement-breakpoint
DROP TABLE "content_planner_channels" CASCADE;--> statement-breakpoint
DROP TABLE "content_planner_intents" CASCADE;--> statement-breakpoint
DROP TABLE "content_planner_topic_types" CASCADE;--> statement-breakpoint
ALTER TABLE "tickets" DROP CONSTRAINT "tickets_priority_id_ticket_priorities_id_fk";
--> statement-breakpoint
ALTER TABLE "ticket_checklist" ALTER COLUMN "title" SET DATA TYPE text;--> statement-breakpoint
ALTER TABLE "tickets" ALTER COLUMN "status" SET DEFAULT 'open';--> statement-breakpoint
ALTER TABLE "companies" ADD COLUMN "active_team_id" uuid;--> statement-breakpoint
ALTER TABLE "companies" ADD COLUMN "active_manager_id" uuid;--> statement-breakpoint
ALTER TABLE "companies" ADD COLUMN "active_time" integer DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE "companies" ADD COLUMN "is_customer" boolean DEFAULT false NOT NULL;--> statement-breakpoint
ALTER TABLE "ticket_checklist" ADD COLUMN "completed_at" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "ticket_checklist" ADD COLUMN "completed_by_user_id" uuid;--> statement-breakpoint
ALTER TABLE "ticket_checklist" ADD COLUMN "completion_note" text;--> statement-breakpoint
ALTER TABLE "ticket_priorities" ADD COLUMN "description" text DEFAULT '';--> statement-breakpoint
ALTER TABLE "ticket_statuses" ADD COLUMN "is_deletable" boolean DEFAULT true NOT NULL;--> statement-breakpoint
ALTER TABLE "ticket_statuses" ADD COLUMN "is_active" boolean DEFAULT true NOT NULL;--> statement-breakpoint
ALTER TABLE "ticket_time_tracker" ADD COLUMN "job_type" varchar(64);--> statement-breakpoint
ALTER TABLE "ticket_time_tracker" ADD COLUMN "duration_adjustment" integer;--> statement-breakpoint
ALTER TABLE "ticket_time_tracker" ADD COLUMN "note" text;--> statement-breakpoint
ALTER TABLE "ticket_types" ADD COLUMN "description" text DEFAULT '';--> statement-breakpoint
ALTER TABLE "ticket_types" ADD COLUMN "is_agent_only" boolean DEFAULT false NOT NULL;--> statement-breakpoint
ALTER TABLE "tickets" ADD COLUMN "contact_user_id" uuid;--> statement-breakpoint
ALTER TABLE "tickets" ADD COLUMN "priority" integer DEFAULT 0;--> statement-breakpoint
ALTER TABLE "tickets" ADD COLUMN "project_id" uuid;--> statement-breakpoint
ALTER TABLE "tickets" ADD COLUMN "project_status_id" integer;--> statement-breakpoint
ALTER TABLE "company_daily_active_assignments" ADD CONSTRAINT "company_daily_active_assignments_company_id_companies_id_fk" FOREIGN KEY ("company_id") REFERENCES "public"."companies"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "customer_weekly_recap_cells" ADD CONSTRAINT "customer_weekly_recap_cells_team_id_teams_id_fk" FOREIGN KEY ("team_id") REFERENCES "public"."teams"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "customer_weekly_recap_cells" ADD CONSTRAINT "customer_weekly_recap_cells_company_id_companies_id_fk" FOREIGN KEY ("company_id") REFERENCES "public"."companies"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "project_statuses" ADD CONSTRAINT "project_statuses_project_id_projects_id_fk" FOREIGN KEY ("project_id") REFERENCES "public"."projects"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "system_activity_log" ADD CONSTRAINT "system_activity_log_actor_user_id_users_id_fk" FOREIGN KEY ("actor_user_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ticket_ai_summaries" ADD CONSTRAINT "ticket_ai_summaries_ticket_id_tickets_id_fk" FOREIGN KEY ("ticket_id") REFERENCES "public"."tickets"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ticket_ai_summaries" ADD CONSTRAINT "ticket_ai_summaries_focal_comment_id_ticket_comments_id_fk" FOREIGN KEY ("focal_comment_id") REFERENCES "public"."ticket_comments"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ticket_ai_summaries" ADD CONSTRAINT "ticket_ai_summaries_created_by_user_id_users_id_fk" FOREIGN KEY ("created_by_user_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "company_daily_active_assignments_snapshot_date_idx" ON "company_daily_active_assignments" USING btree ("snapshot_date");--> statement-breakpoint
CREATE INDEX "customer_weekly_recap_cells_team_week_idx" ON "customer_weekly_recap_cells" USING btree ("team_id","week_start");--> statement-breakpoint
CREATE INDEX "customer_weekly_recap_cells_company_idx" ON "customer_weekly_recap_cells" USING btree ("company_id");--> statement-breakpoint
CREATE UNIQUE INDEX "recap_snapshots_upsert_idx" ON "recap_snapshots" USING btree ("team_key","period_start","period_end","title");--> statement-breakpoint
CREATE INDEX "recap_snapshots_period_idx" ON "recap_snapshots" USING btree ("period_start","period_end");--> statement-breakpoint
CREATE INDEX "system_activity_log_category_created_at_idx" ON "system_activity_log" USING btree ("category","created_at");--> statement-breakpoint
CREATE INDEX "system_activity_log_entity_created_at_idx" ON "system_activity_log" USING btree ("entity_type","entity_id","created_at");--> statement-breakpoint
CREATE UNIQUE INDEX "ticket_ai_summaries_anchor_unique" ON "ticket_ai_summaries" USING btree ("ticket_id","anchor_type","focal_comment_id");--> statement-breakpoint
ALTER TABLE "screenshots" ADD CONSTRAINT "screenshots_project_id_projects_id_fk" FOREIGN KEY ("project_id") REFERENCES "public"."projects"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ticket_checklist" ADD CONSTRAINT "ticket_checklist_completed_by_user_id_users_id_fk" FOREIGN KEY ("completed_by_user_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ticket_time_tracker" ADD CONSTRAINT "ticket_time_tracker_job_type_job_types_slug_fk" FOREIGN KEY ("job_type") REFERENCES "public"."job_types"("slug") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tickets" ADD CONSTRAINT "tickets_project_id_projects_id_fk" FOREIGN KEY ("project_id") REFERENCES "public"."projects"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tickets" ADD CONSTRAINT "tickets_project_status_id_project_statuses_id_fk" FOREIGN KEY ("project_status_id") REFERENCES "public"."project_statuses"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ai_token_usage" DROP COLUMN "company_content_planner_id";--> statement-breakpoint
ALTER TABLE "tickets" DROP COLUMN "priority_id";