export { default as TabGeneral } from './TabGeneral'
export { default as TabAssignees } from './TabAssignees'
export { default as TabTimeTracker } from './TabTimeTracker'
export { default as TabAttributes } from './TabAttributes'
export { default as TabScreenshots } from './TabScreenshots'
export { default as TabActivity } from './TabActivity'
